### PR TITLE
Switch license from GPLv3 to AGPLv3

### PR DESCRIPTION
**Pull request by CrsiX**
I hereby propose switching from GPLv3 to AGPLv3 for the MateBot core API project. I ask you to approve this change to show your consent.

All versions before this commit still remain licensed under GLPv3, while future changes, files & releases will be licensed under AGPLv3. See cb06a07b192beef65e35e389f948949c0a687235 when GLPv3 was added to this project.

### CODE REVIEW

**Review by M4GNV5 — APPROVED** [review]
Apart from the failing CI Tests this looks good :+1:

**Comment by CrsiX** [comment]
The CI tests are failing due to changes in the dependencies, namely uvicorn. They are fixed on the `dev` branch. The CI job one commit before also succeeded, so this is fine.

**Review by myOmikron — APPROVED** [review]
Sounds good to me

**Review by gammelalf — APPROVED** [review]
🤷👍️

**Pull request merged**
